"""Invoke MinerU as an external parser and collect its structured outputs."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import re
import tempfile
from functools import lru_cache
from pathlib import Path
from typing import Any

from .errors import MineruIncompleteOutputError, MineruRuntimeUnavailableError


def _mineru_command_arg(value: str | Path, *, label: str) -> str:
    """Validate a path or executable string before passing it to MinerU argv."""

    value_str = str(value)
    if not re.match(r"^[\w /\\.:~()+\-@=,\[\]!']+$", value_str):
        raise ValueError(f"Unsafe {label} for MinerU command")
    if value_str.startswith("-"):
        raise ValueError(f"Unsafe {label} for MinerU command")
    return value_str


def build_mineru_command(
    input_pdf: Path, output_dir: Path, mineru_bin: str = "mineru"
) -> list[str]:
    """Build the MinerU CLI command for OCR pipeline execution."""

    return [
        _mineru_command_arg(mineru_bin, label="MinerU executable"),
        "-p",
        _mineru_command_arg(input_pdf, label="input PDF path"),
        "-o",
        _mineru_command_arg(output_dir, label="output directory path"),
        "-b",
        "pipeline",
        "-m",
        "ocr",
        "-l",
        "japan",
    ]


@lru_cache
def _cached_which(cmd: str) -> str | None:
    """Cache shutil.which to avoid redundant filesystem lookups."""
    return shutil.which(cmd)


def _resolve_mineru_bin() -> str:
    """Resolve the MinerU executable path for this process.

    The shutil.which result is cached, but NEWSDOM_MINERU_BIN is evaluated
    on every call to allow runtime overrides.
    """

    configured = os.environ.get("NEWSDOM_MINERU_BIN")
    if configured:
        return configured
    found = _cached_which("mineru")
    if not found:
        raise FileNotFoundError(
            "Could not find 'mineru' executable. "
            "Ensure it is installed and on the PATH, or set NEWSDOM_MINERU_BIN."
        )
    return found


def _find_output_dir(base_output_dir: Path) -> Path:
    """Locate the OCR output directory created by MinerU."""

    candidates = list(base_output_dir.glob("*/ocr"))
    if not candidates:
        raise FileNotFoundError("MinerU OCR output directory was not produced")
    return candidates[0]


def _execute_mineru(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    """Execute the MinerU command and handle runtime errors."""
    try:
        return subprocess.run(
            cmd, check=True, capture_output=True, text=True, timeout=300, shell=False
        )
    except subprocess.TimeoutExpired as exc:
        stdout_str = (
            exc.stdout.decode("utf-8", "replace")
            if isinstance(exc.stdout, bytes)
            else exc.stdout
        )
        raise MineruRuntimeUnavailableError(
            returncode=-1,
            stdout=stdout_str or "",
            stderr="OCR processing timed out after 5 minutes",
        ) from exc
    except subprocess.CalledProcessError as exc:
        raise MineruRuntimeUnavailableError(
            returncode=exc.returncode,
            stdout=exc.output,
            stderr=exc.stderr,
        ) from exc
    except FileNotFoundError as exc:
        raise MineruRuntimeUnavailableError() from exc


def _read_mineru_json(path: Path, *, artifact: str) -> Any:
    """Read a MinerU JSON artifact with safe, differentiated failure messages."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise MineruIncompleteOutputError(f"{artifact} JSON was malformed") from exc
    except (OSError, UnicodeDecodeError) as exc:
        raise MineruIncompleteOutputError(f"{artifact} JSON could not be read") from exc


def _parse_mineru_output(
    output_dir: Path, input_pdf: Path
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Parse the JSON outputs generated by MinerU."""
    try:
        ocr_dir = _find_output_dir(output_dir)
        content_path = ocr_dir / f"{input_pdf.stem}_content_list.json"
        if not content_path.exists():
            try:
                content_path = next(ocr_dir.glob("*_content_list.json"))
            except StopIteration:
                raise FileNotFoundError("MinerU content list JSON was not produced")
        try:
            model_path = next(ocr_dir.glob("*_model.json"))
        except StopIteration:
            raise FileNotFoundError("MinerU model JSON was not produced")
    except FileNotFoundError as exc:
        raise MineruIncompleteOutputError() from exc
    content_list = _read_mineru_json(content_path, artifact="content list")
    model = _read_mineru_json(model_path, artifact="model")

    return content_list, model


def run_mineru(input_pdf: Path) -> dict[str, Any]:
    """Run MinerU on a PDF and return parsed JSON artifacts plus raw process output.

    PATH lookups for the default MinerU executable are cached, while
    NEWSDOM_MINERU_BIN is evaluated on each call to allow runtime overrides.
    """

    mineru_bin = _resolve_mineru_bin()
    with tempfile.TemporaryDirectory(prefix="newsdom-mineru-") as tempdir:
        output_dir = Path(tempdir)
        cmd = build_mineru_command(input_pdf, output_dir, mineru_bin=mineru_bin)

        completed = _execute_mineru(cmd)
        content_list, model = _parse_mineru_output(output_dir, input_pdf)

        return {
            "content_list": content_list,
            "model": model,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
        }
